name: CI/CD Auth Service

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push-to-yc:
    runs-on: ubuntu-latest
    steps:
      # 1. Клонируем репозиторий
      - uses: actions/checkout@v3

      # 2. Устанавливаем JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3. Собираем JAR с jOOQ и остальным
      - name: Build JAR
        run: ./gradlew clean build -x test

      # 4. Сборка Docker-образа auth_service
      - name: Build docker image
        run: |
          docker build . \
            --file Dockerfile \
            --tag cr.yandex/${{ secrets.YC_REGISTRY_ID }}/auth_service:latest

      # 5. Логинимся в YC Container Registry
      - name: Login to YC Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}

      # 6. Пушим образ в YC Registry
      - name: Push tag to YC Registry
        run: |
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/auth_service:latest
